In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
#scalar tensor
scalar = torch.tensor(7) #create a tensor useing this code = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim #finds the dimentions

0

In [4]:
#vector tensor
vector = torch.tensor([6,7])
vector

tensor([6, 7])

In [5]:
vector.ndim

1

In [6]:
# MATRIX tensor
matrix = torch.tensor([[6,7],
                       [6,9]])
matrix

tensor([[6, 7],
        [6, 9]])

In [7]:
matrix.ndim

2

In [8]:
matrix[1]

tensor([6, 9])

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
# TENSOR
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[5,2,3],
                        [4,6,7],
                        [7,8,9]]])

In [11]:
tensor.ndim

3

In [12]:
tensor.shape

torch.Size([2, 3, 3])

In [13]:
tensor[1]

tensor([[5, 2, 3],
        [4, 6, 7],
        [7, 8, 9]])

In [14]:
#creates random tensors
random_tensor = torch.rand(5,4)
random_tensor

tensor([[0.2517, 0.6292, 0.3890, 0.6160],
        [0.3852, 0.4692, 0.9388, 0.0612],
        [0.3968, 0.6833, 0.9305, 0.3506],
        [0.4935, 0.7096, 0.9941, 0.8188],
        [0.0261, 0.2808, 0.2890, 0.4766]])

In [15]:
random_tensor.ndim

2

In [16]:
random_image_size_tensor = torch.rand(size=(254,254,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([254, 254, 3]), 3)

Ones and Zeros

In [17]:
#create a tensor with all zeros
zeros = torch.zeros(size=(5,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
#create tensor with ones
ones = torch.ones(size=(5,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
ones.dtype#tells the default data type

torch.float32

Createing range of tensors and tensors-like

In [20]:
one_to_tohousand = torch.arange(start = 1, end = 1000, step = 67)
one_to_tohousand
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#creating toensers like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor DataTypes


In [22]:
float_32_tensor = torch.tensor([3.0,5.0,9.0],
                               dtype=None, # data type(eg. float32 or float16 etc)
                               device="cuda", #what device the tensor on
                               requires_grad=False) # whether to track gradiants with this tensor operations
float_32_tensor

tensor([3., 5., 9.], device='cuda:0')

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [25]:
float_16_tensor * float_32_tensor

tensor([ 9., 25., 81.], device='cuda:0')

In [26]:
tensor = torch.tensor([1,2,3])


In [27]:
tensor + 10

tensor([11, 12, 13])

In [28]:
tensor * 10

tensor([10, 20, 30])

In [29]:
tensor - 10

tensor([-9, -8, -7])

In [30]:
# pytorch built-in finctions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [31]:
torch.add(tensor, 2)

tensor([3, 4, 5])

Matrix multiplication

2 ways-

1. element wise multiplication
2. matrix multiplication (dot product)

In [32]:
# element wise multiplications

tensor * tensor

tensor([1, 4, 9])

In [33]:
# matrix multiplication (dot product)

torch.matmul(tensor, tensor)

tensor(14)

In [34]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)

In [35]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [36]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [37]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

tensor aggrigation(min,max,sum,mean(avg)), etc


In [38]:
#create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [39]:
#find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [40]:
#find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [41]:
#find avg NOTE- mean only uses float 32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [42]:
# find sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [43]:
# find the index of the min in the tensor
x.argmin()


tensor(0)

In [44]:
# find the index of the max in the tensor
x.argmax()

tensor(9)

Reshaping, stacking,  squeezing and unsqueezing tensors

In [45]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [46]:
# add an extra diemention
# the number that go in reshape have to be the multiple of the original shape
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# change the view
# Change view (keeps same data as original but changes view)
#changeing z will change x
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
z[:, 1] = 5
z, x

(tensor([[1., 5., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 5., 3., 4., 5., 6., 7., 8., 9.]))

In [49]:
x_stacked = torch.stack([x,x,x,x,x,x,x], dim= 1)
x_stacked

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [5., 5., 5., 5., 5., 5., 5.],
        [3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9., 9., 9.]])

In [50]:
t = torch.rand(1,2,3)
t

tensor([[[0.3570, 0.7054, 0.2057],
         [0.3266, 0.7177, 0.4068]]])

In [51]:
x_reshaped

tensor([[1., 5., 3., 4., 5., 6., 7., 8., 9.]])

In [52]:
# squezzing a tensor removeing the single dim
x_squeeze = x_reshaped.squeeze()
x_squeeze, x_squeeze.shape

(tensor([1., 5., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
# un squezzing a tensor
x_unsquezzed = x_squeeze.unsqueeze(dim = 0)
x_unsquezzed, x_unsquezzed.shape

(tensor([[1., 5., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# permute = rearranges the dims of the tensor in a givein order by the humen
a = torch.rand(size= (255, 255, 3))
a.shape


torch.Size([255, 255, 3])

In [55]:
a_permuted = a.permute((2,1,0))
a_permuted.shape

torch.Size([3, 255, 255])

In [56]:
a[0,0,0] = 67

In [57]:
a_permuted = a.permute((2,1,0))
a_permuted[0,0,0]

tensor(67.)

Indexing: get a piece of data from a part of the tensor

In [58]:
b = torch.arange(1, 10).reshape(1, 3, 3)
b, b.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
b[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [60]:
b[0, 1]

tensor([4, 5, 6])

In [61]:
b[0,2,2]

tensor(9)

In [62]:
#":" also can use : to get all the values of the dimention
b[:, 0]

tensor([[1, 2, 3]])

In [63]:
b[:, :, 1]

tensor([[2, 5, 8]])

Turning numpy array into pythorch tensor and vice ver ca

In [64]:
#numpy array -> tensor
import torch 
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [65]:
array.dtype

dtype('float64')

In [66]:
tensor.dtype

torch.float64

In [67]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reprodusability (trying to take out random out of random)

In [68]:
import torch

random_1 = torch.rand(3,4)
random_2 = torch.rand(3,4)
print(random_1)
print(random_2)
print(random_1 == random_2)

tensor([[0.4587, 0.4899, 0.1309, 0.7466],
        [0.3430, 0.5261, 0.2209, 0.7269],
        [0.3242, 0.9113, 0.5217, 0.6262]])
tensor([[0.5775, 0.0670, 0.9431, 0.2214],
        [0.6305, 0.1301, 0.2704, 0.3421],
        [0.1420, 0.7922, 0.6664, 0.4872]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [70]:
#reprodusability
random_seed = 67
torch.manual_seed(random_seed)
random_3 = torch.rand(3, 4)
torch.manual_seed(random_seed)
random_4 = torch.rand(3,4)

print(random_3)
print(random_4)
print(random_3 == random_4)

tensor([[0.7380, 0.3646, 0.8673, 0.5464],
        [0.5885, 0.9785, 0.8875, 0.9903],
        [0.3595, 0.3245, 0.8871, 0.9991]])
tensor([[0.7380, 0.3646, 0.8673, 0.5464],
        [0.5885, 0.9785, 0.8875, 0.9903],
        [0.3595, 0.3245, 0.8871, 0.9991]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
